[package]
name = "cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
cat = { path = "../cat" }
actor_io = { path = "../actor_io" }
actor_runtime = { path = "../actor_runtime" }
ailetos = { path = "../ailetos" }
embedded-io.workspace = true
tokio = { version = "1", features = ["rt", "macros"] }
futures = "0.3"
rusqlite = { version = "0.32", features = ["bundled"] }
parking_lot = "0.12"
