[package]
name = "cat"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
actor_io.workspace = true
actor_runtime.workspace = true
embedded-io.workspace = true
getrandom.workspace = true
